name: Android CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.22.1'

    - name: Setup Android NDK
      uses: android-actions/setup-android-ndk@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # - name: Build with Gradle
    #   run: ./gradlew assembleRelease
    - name: Run tests
      run: ./gradlew test
      
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/
        retention-days: 7

    # 可选：上传 mapping 文件用于崩溃分析
    - name: Upload mapping files
      uses: actions/upload-artifact@v4
      with:
        name: mapping-files
        path: app/build/outputs/mapping/release/
        retention-days: 7
